defaults:
  run:
    shell: bash
    working-directory: infrastructure
name: Deploy
on: [push, pull_request]
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Prepare
        run: |
          terraform init
          terraform plan
      
